# Generated by Django 3.2.3 on 2021-05-20 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('WT', 'WAITING'), ('AD', 'ADMITTED'), ('DS', 'DISCHARGED')], default='WT', max_length=2),
        ),
    ]
